import { NextResponse } from "next/server"
import { getFormatter, getTranslations } from "next-intl/server"
import { APP_NAME } from "@/config/brand"
import { APP_TIME_ZONE } from "@/lib/date-format"
import { loadMemberCardEligibility } from "@/lib/member-card/loader"
import { ensureMemberCardToken } from "@/lib/member-card/token"
import { memberCardVerificationUrl } from "@/lib/member-card/url"
import { buildMemberCardViewModel } from "@/lib/member-card/view-model"
import { buildMemberCardPdf, memberCardPdfFilename } from "@/lib/pdf/member-card-pdf"

// Everything the two card-PDF routes (the member's own, and a manager's) do once they have
// decided *who* the card is for. Only the authorization differs between them, so keeping the
// rest here is what guarantees a member downloading their card and a manager printing the
// same member's card get byte-for-byte the same document.
//
// Both refusals are deliberately mute: French, no name, no association, no reason beyond the
// state — a card PDF URL is one guessed id away from being an enumeration oracle, and the
// caller already has a screen explaining why there is no card.
const NO_CARD_FOUND     = "Carte de membre introuvable"
const NO_CARD_PRINTABLE = "Aucune carte de membre à imprimer"

/**
 * `inline` hands the PDF to the browser's own viewer, which is how printing works (see
 * memberCard.portal.print): one renderer, so what comes out of the printer is exactly what
 * the download contains. Anything else — including a missing parameter — downloads.
 */
function contentDisposition(request: Request, filename: string): string {
  const requestedDisposition = new URL(request.url).searchParams.get("disposition")
  const disposition = requestedDisposition === "inline" ? "inline" : "attachment"
  // filename is already ASCII (memberCardPdfFilename slugs it), so the plain form is enough
  // and no RFC 5987 filename* is needed.
  return `${disposition}; filename="${filename}"`
}

/**
 * The A4 sheet carrying one member's card, or the reason there is none. Callers are
 * responsible for authorization: `membreId` must already have been proven to belong to this
 * association *and* to be a member this caller may see (the portal route resolves it through
 * loadPortalHousehold, the manager route through withAdminAuth's role allowlist).
 */
export async function memberCardPdfResponse(
  request: Request,
  associationId: string,
  membreId: string,
): Promise<NextResponse> {
  // Scoped by associationId inside the loader — a membreId from another tenant comes back
  // null and is answered exactly like a membreId that doesn't exist at all.
  const loaded = await loadMemberCardEligibility(associationId, membreId)
  if (!loaded) return NextResponse.json({ error: NO_CARD_FOUND }, { status: 404 })

  // Only the two states that can actually be printed. An unpaid or cancelled membership has
  // no card, and minting a token for one would hand out a permanent public URL pointing at a
  // member who was never shown a card — 409, because the request is well-formed and the
  // member exists, it is the membership that isn't there yet.
  const { eligibility } = loaded
  if (eligibility.state !== "valid" && eligibility.state !== "expired") {
    return NextResponse.json({ error: NO_CARD_PRINTABLE }, { status: 409 })
  }

  // The live token, not a fresh one: a card regenerated by a manager must invalidate the QR
  // on every sheet already printed, which only works if every surface prints the same token.
  const cardToken = await ensureMemberCardToken(associationId, membreId)
  const card      = cardToken ? buildMemberCardViewModel(loaded, memberCardVerificationUrl(cardToken)) : null
  if (!card) return NextResponse.json({ error: NO_CARD_FOUND }, { status: 404 })

  const translate = await getTranslations("memberCard")
  const formatter = await getFormatter()

  // Explicit time zone, exactly like <MemberCard />: a cotisation covering a calendar year
  // ends at 31 December 23:59 Paris, which a server running in UTC would print as the 30th —
  // and the printed date must match the one the member sees on screen.
  const cardDate = formatter.dateTime(card.validUntil, {
    day: "2-digit", month: "2-digit", year: "numeric", timeZone: APP_TIME_ZONE,
  })

  // An expired card carries the day its membership *stopped* covering (see
  // buildMemberCardViewModel), and the sheet deliberately has no status line of its own, so
  // this single line is all the paper says about validity: printed as "Valable jusqu'au
  // 31/12/2024" it would read as a card that is still good to anyone glancing at it. The
  // screen card keeps its own "Adhésion expirée" badge and is untouched.
  const validityLabel = card.state === "expired"
    ? translate("card.expiredOn",  { date: cardDate })
    : translate("card.validUntil", { date: cardDate })

  const pdf = await buildMemberCardPdf({
    card,
    // Translated here rather than in the renderer: buildMemberCardPdf takes finished strings
    // so it never has to reach for a request context.
    labels: {
      documentTitle: translate("print.documentTitle", { name: card.memberName }),
      validity:      validityLabel,
      generatedBy:   translate("card.generatedBy", { appName: APP_NAME }),
      cutGuide:      translate("print.guide"),
    },
  })

  return new NextResponse(new Uint8Array(pdf), {
    headers: {
      "Content-Type":        "application/pdf",
      "Content-Disposition": contentDisposition(request, memberCardPdfFilename(loaded.membre.lastName, loaded.membre.firstName)),
      // Eligibility is recomputed live on every request and the QR token can be rotated at
      // any moment, so a cached sheet would be a stale claim of membership.
      "Cache-Control":       "private, no-store",
    },
  })
}
