-- CreateEnum
CREATE TYPE "DonorType" AS ENUM ('INDIVIDUAL', 'COMPANY');

-- CreateEnum
CREATE TYPE "OrganismeCategory" AS ENUM ('ASSOCIATION_LOI_1901', 'FONDATION_RECONNUE_UTILITE_PUBLIQUE', 'FONDATION_UNIVERSITAIRE_PARTENARIALE', 'FONDATION_ENTREPRISE', 'MUSEE_DE_FRANCE', 'AIDE_ALIMENTAIRE_SOCIALE', 'AUTRE_INTERET_GENERAL', 'ASSOCIATION_CULTUELLE_ALSACE_MOSELLE', 'ETABLISSEMENT_ENSEIGNEMENT_SUPERIEUR', 'ETABLISSEMENT_ENSEIGNEMENT_SUPERIEUR_CONSULAIRE', 'ORGANISME_RECHERCHE_SCIENTIFIQUE', 'ORGANISME_SPECTACLE_EXPOSITIONS', 'PROJET_THESE_DOCTORAT', 'SOCIETE_EXPOSITIONS_UNIVERSELLES', 'SOCIETE_PROGRAMME_AUDIOVISUEL', 'FONDATION_PATRIMOINE', 'FONDS_DOTATION', 'ORGANISME_AIDE_PME', 'FEDERATION_ORGANISMES_AGREES', 'ORGANISME_PROTECTION_BIENS_CULTURELS', 'ORGANISME_UE_SIMILAIRE');

-- AlterTable
ALTER TABLE "Association" ADD COLUMN     "objet" TEXT,
ADD COLUMN     "organismeCategory" "OrganismeCategory" NOT NULL DEFAULT 'ASSOCIATION_LOI_1901',
ADD COLUMN     "organismeCategoryDetail" TEXT;

-- AlterTable
ALTER TABLE "Don" ADD COLUMN     "companyName" TEXT,
ADD COLUMN     "donorType" "DonorType" NOT NULL DEFAULT 'INDIVIDUAL',
ADD COLUMN     "siret" TEXT;
